name: android-feature

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release*'
  pull_request:
    branches:
      - '*'
      - '!master'
      - '!release*'

jobs:
  
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
    
      - name: Assemble app debug APK
        run: bash ./gradlew assembleDebug --stacktrace
        
      - name: Upload app APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Assemble Android Instrumentation Tests
        run: bash ./gradlew assembleDebugAndroidTest
        
      - name: Upload Android Test APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug-androidTest
          path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
    
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    # Allows test to see the repo
    - uses: actions/checkout@v1
    
    # Sets up JDK version
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    # Runs Unit Test Action
    - name: Unit Tests
      run: bash ./gradlew test

  firebase:
    name: Firebase Test Lab
    needs: apk
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Download app APK
        uses: actions/download-artifact@v1
        with:
          name: app-debug

      - name: Download Android test APK
        uses: actions/download-artifact@v1
        with:
          name: app-debug-androidTest

      - name: Login to Google Cloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_key: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAidG91cnRyZWstNjE4OTMiLAogICJwcml2YXRlX2tleV9pZCI6ICIyOTk0ZmJiOGVjNGMyMTRjYTIyMDVmOTk0MWU5Mjc5NTc2OTNkZDYzIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdXdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLVXdnZ1NoQWdFQUFvSUJBUUNkUDNydXlyL0dCT0w5XG5FRDVTOUpwalhXSFJhK2d6TDhGbnM5OG1VUXR2ZTF6aWU2dk40TWVoWXlBOC9uTDVJRmc1eGxUbG5QYUtWTVQ1XG5nWkdtRW5LeUM4Ri9GektBQmp4VzZVQzBZek1naVRjWE9CcE5PckJxQkVERHhkMUgrbDR0N1kwR20wU1c2U0NrXG5UTDg2VHlBV09zZzA3LzY3MUdhS3BIb0NLV1VFVmtKMU12YklmdFIydnBLRVRuSmQwY3lQclZubUpyeml5cUdOXG43Z3U2T2NlUjVDbGNEN0xhVk9OQWFmbitNa0JSZTQzRTVHWjRBUGROVjFIMmZVRWNST21VMnBoRjZtWE1PYWhrXG55V2EzRFQyem43eENyZGpadGhoemtWVW9BckRFMUdqck43a24wbjRDQWduYzRQYW10TVZaR0ZUanBlNXlLQ2pyXG56YU01dzRSM0FnTUJBQUVDZ2Y5YVN4bE1CU0FabExUQ201RXVFVWFWeUFsak41TWQwVTQ5UGd2azlLU2NYem4yXG4wd3pVS3o1MmJYVVZrUVowQng2aURrQ3htRy80L3JRY2tVb1JFb2JKdGZabUErdjdsNWtPVHVIWXN4Mm9rU0lSXG5NeVhuTXN3YUZGY2NFNEg4MHNkQm1DWmlwTVc5NGgvY09EV1dSZGttNnBvTHk4TjZGM3pLSDZmdmxkVnJweldpXG5pME9LMmZhMkd3TVFIN0JlR1NIK21hMDVTRnloaHRvcWF1UkhKT0E3SnBVaExsVWFOeE5WRUNnVHdZazl1Nk5DXG5BNFBNanVnOWZ0M2laZ3FOUXQ5MTdTZmhDb3pCZ21odGdlOHlDWHlEZklscnlyR2xvaHg5SC9aNU95Uk44SkQvXG5TYXdZaXB1b2xZU0VKQ1I1Vm0wUlJYRjd2MjUyaDVSRnJnUDM0M0VDZ1lFQTFaLytacjEwbmFEWHkyL1MwYTVqXG5scXMzbklEeHhveG5qVUZYN1RVVUpmSEViUGpNdjY4WDNwc0FicG1jYzRZeEJnbll1bkFtTkRLRnlIL21OazhoXG5Td0UvRnk2Vm9tOCtrcXJxR01nMjMremVXdVJkVjVhT1VaRGpiSXlycjlHWlZrVmU2VUIvaGdraldKbW5NT041XG5TVGRNZU1Nbi9MZXllV0U1MVY5Ui9FOENnWUVBdkhDZ3RqU2lsYU5IQ3JSMjFkRGp3c3JOWXlUWHBLTTA5WHpnXG41MUtVMGJ2eENrUlRqMmo2aUF2clRqSTc2bWVPcU5YR2FIQTNrckdnbHJ2SnJOak5pK2VNZjdBOVlIT0VZTGhIXG5LZUQwaHAwQnVsaUVqTEJNeE81MVpQUFJsQXQ0UUFsZHZkSU4wdzF1N2dwWnRzSmxkSFhxVVR3RjdlRFhJdE5FXG43NDM4STFrQ2dZQkErSFFMRXp2UVpRYThuTG5sZzhCT0pxeTNNSkJYN29QZjlpdWp2U3p2aldSTU1DODFiUzg1XG5TTE1NOERNZy80TVJieFUzUHJ5ZnkyM2MyT2xQUXluQkFoUUtIT1R0amgvZHc1V0hDLzJFaFNuclF1RVFybjJDXG5XU3FSN1FhYVpvallNQ2o1aitBNUI3WjBUK2NGZTJsNzF4R3UrTXZFbEtuM09KYTZTazlKQ1FLQmdCUnpCSDNCXG5hSU5rbktrRXZJQ25rby9wQWpEb0pwNnZOMmdNalR1Tk1xa3dCQkJoS2RBK1RESEhXVm03Q2RWK04zVUsvZVVIXG5pSUJhMWxxRk5uV1RjWHJsUGRIOWhpdVpYWnhCWXplZ09la0IwTll3RlBKUGo0VXZlMzNoRjdWQktXT0pvS3FnXG55TzlHWGV0bkpDVTVJMWxvRW0yT1hmWmFsLzRuZnl1ZjlPVEJBb0dCQUladk94dXhHWENWYjJNcFlqUzNxMGdZXG5SRzlsOUp3dEdZejVZOUhWUVNwVGQ0aG5lV2pnUVExNDRDZUorMUZ6K25pRDE2dGJXelI4ZlJtZnh4V1pKUy9CXG5OZEYxL3F0NkVqeERybytlUFIzcytyejZkUWJseExHQndnb1VDd25YR2F3UTF3STBhU3dmS05YOFh4OEdycWlPXG5rd1cyYWVRajNkdnlwbDRIbm4wdFxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogImZpcmViYXNlLWFkbWluc2RrLWd3Zmg4QHRvdXJ0cmVrLTYxODkzLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjEwNzg1MjY4ODIyNzIxMDAzODY0OSIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvZmlyZWJhc2UtYWRtaW5zZGstZ3dmaDglNDB0b3VydHJlay02MTg5My5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIKfQo

      - name: Set current project
        run: gcloud config set project tourtrek-61893

      - name: Run Instrumentation Tests in Firebase Test Lab
        run: gcloud firebase test android run --type instrumentation --app app-debug/app-debug.apk --test app-debug-androidTest/app-debug-androidTest.apk --device model=Pixel2,version=28,locale=pl,orientation=portrait