name: Android Feature Branch CI

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release*'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
    # Allows test to see the repo
    - uses: actions/checkout@v1
    
    # Sets up JDK version
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    # Runs Unit Tests
    - name: Unit Tests
      run: bash ./gradlew test
