name: Android Feature Branch CI

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release*'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    # Allows test to see the repo
    - uses: actions/checkout@v1
    
    # Sets up JDK version
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    # Runs Unit Test Action
    - name: Unit Tests
      run: bash ./gradlew test
    
    # Run the Firebase Test Lab Action
    - name: Firebase Test Lab Tests
      uses: asadmansr/Firebase-Test-Lab-Action@v1.0
      with:
        arg-spec: 'firebase-tests.yml:android-pixel-4'
      env:
        SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
    
      
