name: android-feature

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release*'
  pull_request:
    branches:
      - '*'
      - '!master'
      - '!release*'

jobs:
  
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
    
      - name: Assemble app debug APK
        run: bash ./gradlew assembleDebug --stacktrace
        
      - name: Upload app APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Assemble Android Instrumentation Tests
        run: bash ./gradlew assembleDebugAndroidTest
        
      - name: Upload Android Test APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug-androidTest
          path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
    
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    # Allows test to see the repo
    - uses: actions/checkout@v1
    
    # Sets up JDK version
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    # Runs Unit Test Action
    - name: Unit Tests
      run: bash ./gradlew test